import type { Metadata } from "next";
import "./globals.css";
import Header from "@/Components/Layouts/Header";
import Footer from "@/Components/Layouts/Footer";
import localFont from 'next/font/local'
import { Open_Sans } from 'next/font/google'


const NeoSans = localFont({
  src: [
    {
      path: './fonts/Neo_Sans_Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/NeoSansPro-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/NeoSansMediumTR.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/NeoSansBoldTR.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-neo',
});

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '700'], // include weights you need
  display: 'swap',
  variable: '--font-open-sans',
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <body className={`${NeoSans.variable} ${openSans.variable} antialiased`}>

        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
